{
	"version": 1565542388,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/player-sheet0.png",
		"images/nmy1dmy-sheet0.png",
		"images/playerb-sheet0.png",
		"images/nmybdmy-sheet0.png",
		"images/playernrg.png",
		"images/particles.png",
		"images/star-sheet0.png",
		"images/star-sheet1.png",
		"images/star-sheet2.png",
		"images/nmyhp.png",
		"images/playerhp.png",
		"images/sign-sheet0.png",
		"images/target-sheet0.png",
		"images/nmy1-sheet0.png",
		"images/shldind-sheet0.png",
		"images/shld-sheet0.png",
		"images/touchspace-sheet0.png",
		"images/nmyeye-sheet0.png",
		"images/nmyeye-sheet1.png",
		"images/nmyeye-sheet2.png",
		"images/nmyb-sheet0.png",
		"images/spritefont.png",
		"images/maingui.png",
		"images/tbguitop.png",
		"images/tbguiright.png",
		"images/guicorner-sheet0.png",
		"images/tbguibot.png",
		"images/tbguileft.png",
		"images/starter-sheet0.png",
		"images/logo0-sheet0.png",
		"images/logo1-sheet0.png",
		"images/logo2-sheet0.png",
		"images/logo3-sheet0.png",
		"images/logo4-sheet0.png",
		"images/explodring-sheet0.png",
		"images/tiledbackground.png",
		"images/sprite-sheet0.png",
		"images/hand-sheet0.png",
		"images/sprite17-sheet0.png",
		"images/spritefont2.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/shieldg.png",
		"images/pbfx-sheet0.png",
		"images/directions-sheet0.png",
		"images/tiledbackground2.png",
		"images/embcount.png",
		"images/tbguileft2.png",
		"images/sprite4-sheet0.png",
		"images/shieldat.png",
		"images/shieatt-sheet0.png",
		"media/sfx2.m4a",
		"media/sfx2.ogg",
		"media/sfx3.m4a",
		"media/sfx3.ogg",
		"media/airshot1.m4a",
		"media/airshot1.ogg",
		"media/airshot2.m4a",
		"media/airshot2.ogg",
		"media/airshot3.m4a",
		"media/airshot3.ogg",
		"media/explosion 1.m4a",
		"media/explosion 1.ogg",
		"media/explosion 2.m4a",
		"media/explosion 2.ogg",
		"media/explosion 3.m4a",
		"media/explosion 3.ogg",
		"media/explosion 4.m4a",
		"media/explosion 4.ogg",
		"media/explosion 5.m4a",
		"media/explosion 5.ogg",
		"media/sfx7.m4a",
		"media/sfx7.ogg",
		"media/lazer ricochet.m4a",
		"media/lazer ricochet.ogg",
		"media/cancel - 4.m4a",
		"media/cancel - 4.ogg",
		"media/shieldsup.m4a",
		"media/shieldsup.ogg",
		"media/radius2.ogg",
		"media/fatswoop.m4a",
		"media/fatswoop.ogg",
		"media/arcitak.m4a",
		"media/arcitak.ogg",
		"media/shieldattack.m4a",
		"media/shieldattack.ogg",
		"media/shortshot.m4a",
		"media/shortshot.ogg",
		"media/onus.ogg",
		"media/onus.m4a",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"facebook.png",
		"instagram.png",
		"patreonmark.png",
		"twitter.png",
		"youtube.png",
		"rawdeflate.js",
		"rawinflate.js",
		"base64-1.7.js",
		"GameAnalytics.js"
	]
}