{
	"version": 1566480872,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/tiledbackground.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/sprite7-sheet1.png",
		"images/sprite8-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/sprite10-sheet0.png",
		"images/sprite10-sheet1.png",
		"images/sprite11-sheet0.png",
		"images/sprite12-sheet0.png",
		"images/sprite13-sheet0.png",
		"images/sprite14-sheet0.png",
		"images/sprite15-sheet0.png",
		"images/tiledbackground2.png",
		"images/sprite16-sheet0.png",
		"images/sprite17-sheet0.png",
		"images/sprite18-sheet0.png",
		"images/sprite19-sheet0.png",
		"images/sprite20-sheet0.png",
		"images/sprite21-sheet0.png",
		"media/bugatti_on_1.m4a",
		"media/bugatti_on_1.ogg",
		"media/bugatti_on_2.m4a",
		"media/bugatti_on_2.ogg",
		"media/bugatti_on_3.m4a",
		"media/bugatti_on_3.ogg",
		"media/bugatti_on_4.m4a",
		"media/bugatti_on_4.ogg",
		"media/shift.m4a",
		"media/shift.ogg",
		"media/ending.m4a",
		"media/ending.ogg",
		"media/intro.m4a",
		"media/intro.ogg",
		"media/countdown circle_option2_nmedit.m4a",
		"media/countdown circle_option2_nmedit.ogg",
		"media/crew race intro_dialogue display_first.m4a",
		"media/crew race intro_dialogue display_first.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}